services:
  pneuma-tailscale:
    image: tailscale/tailscale:latest
    container_name: pneuma-tailscale
    hostname: pneuma
    env_file:
      - .env
    environment:
      - TS_CLIENT_ID
      - TS_CLIENT_SECRET
      - TS_AUTHKEY
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SOCKET=/var/run/tailscale/tailscaled.sock
    volumes:
      - pneuma_ts_state:/var/lib/tailscale
      - pneuma_ts_sock:/var/run/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped

  server:
    image: ghcr.io/johncmanuel/pneuma/server:latest
    container_name: pneuma-server
    restart: unless-stopped
    volumes:
      # Persistent application data (database, cached artwork, uploads, etc.)
      - pneuma_data:/data

      # Mount your music directory (read-only recommended)
      # Replace `./music` with the actual path to your local music directory
      - ../../music:/music:ro

    environment:
      - PNEUMA_SERVER_HOST=0.0.0.0
      # Core configuration
      - PNEUMA_DATA_DIR=/data

      # Point the music scanner to the mounted volume
      - PNEUMA_LIBRARY_WATCH_FOLDERS=/music

      # Security (this'll be auto generated if not provided and placed in the config file)
      # - PNEUMA_AUTH_SECRET_KEY=change-this-to-a-secure-random-string

      # Rate limiting (defaults to true)
      # - PNEUMA_RATE_LIMITING_ENABLED=true

      # Increase upload limit if needed (500 MB is default)
      # - PNEUMA_UPLOAD_MAX_SIZE_MB=500

  caddy:
    image: caddy:2.11.4-alpine
    container_name: pneuma-caddy
    restart: unless-stopped
    network_mode: service:pneuma-tailscale
    depends_on:
      - pneuma-tailscale
    env_file:
      - .env
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
      # fetch certs from tailscale daemon sidecar
      - pneuma_ts_sock:/var/run/tailscale

volumes:
  pneuma_data:
  caddy_data:
  caddy_config:
  pneuma_ts_state:
  pneuma_ts_sock:

networks:
  default:
    driver: bridge
    driver_opts:
      # tailscale's manual transmission unit (MTU) is 1280 bytes, so
      # set docker's MTU to be the same
      # https://tailscale.com/docs/reference/troubleshooting/network-configuration/tcp-connection-two-devices
      com.docker.network.driver.mtu: 1280
